name: Detect breaking changes
on:
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  breaking:
    name: "Detect breaking changes"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Build a JAR
        run: mvn --batch-mode -DskipTests clean package
      - name: Run roseau
        uses: alien-tools/roseau-action@main
        with:
          roseau-version: latest
          v1: io.github.alien-tools:roseau-core:0.5.0
          v2: core/target/roseau-core-0.6.0-SNAPSHOT.jar
          fail-on-bc: false
          reports: HTML=report.html,CSV=report.csv

  not-breaking:
    name: "No breaking changes expected"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: alien-tools/roseau-action@main
        id: roseau
        with:
          v1: com.google.guava:guava:33.5.0-jre
          v2: com.google.guava:guava:33.5.0-jre
          fail-on-bc: true
