name: Detect breaking changes
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  breaking:
    name: "Detect breaking changes"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build the current JAR
        run: mvn --batch-mode -DskipTests clean package
      - name: Run roseau in JAR mode
        uses: alien-tools/roseau-action@main
        with:
          roseau-version: early-access
          v1: io.github.alien-tools:roseau-core:0.5.0
          v2: core/target/roseau-core-0.6.0-SNAPSHOT.jar
          fail-on-bc: false
          reports: HTML=report.html,CSV=report.csv
      - name: Run roseau in sources mode
        uses: alien-tools/roseau-action@main
        with:
          roseau-version: early-access
          v1: io.github.alien-tools:roseau-core:0.5.0
          v2: core/src/main/java
          fail-on-bc: true
          reports: HTML=report.html,CSV=report.csv
