package com.github.maracas.roseau.changes;

public enum BreakingChangeKind {
	ANNOTATION_DEPRECATED_ADDED,
	TYPE_REMOVED,
	TYPE_NOW_ABSTRACT,
	TYPE_NOW_FINAL,
	TYPE_TYPE_CHANGED,
	CLASS_NOW_CHECKED_EXCEPTION,
	TYPE_LESS_ACCESSIBLE,
	CLASS_GENERIC_TEMPLATE_CHANGED,
	CLASS_GENERIC_TEMPLATE_GENERICS_CHANGED,
	SUPERCLASS_MODIFIED_INCOMPATIBLE,



	METHOD_REMOVED,    //
	METHOD_LESS_ACCESSIBLE,  //
	METHOD_LESS_ACCESSIBLE_THAN_IN_SUPERCLASS,
	METHOD_IS_STATIC_AND_OVERRIDES_NOT_STATIC,
	METHOD_RETURN_TYPE_CHANGED,  //
	METHOD_RETURN_TYPE_GENERICS_CHANGED,
	METHOD_PARAMETER_GENERICS_CHANGED,
	METHOD_NOW_ABSTRACT,    //
	METHOD_NOW_FINAL,     //
	METHOD_NOW_STATIC,    //
	METHOD_NO_LONGER_STATIC,    //
	METHOD_NOW_VARARGS,
	METHOD_NO_LONGER_VARARGS,
	METHOD_ADDED_TO_INTERFACE,
	METHOD_NOW_THROWS_CHECKED_EXCEPTION,
	METHOD_NO_LONGER_THROWS_CHECKED_EXCEPTION,
	METHOD_ABSTRACT_ADDED_TO_CLASS,
	METHOD_NEW_DEFAULT,
	METHOD_MOVED_TO_SUPERCLASS,
	METHOD_ABSTRACT_NOW_DEFAULT,  //


	FIELD_STATIC_AND_OVERRIDES_STATIC,
	FIELD_NOW_FINAL,
	FIELD_NOW_STATIC,
	FIELD_NO_LONGER_STATIC,
	FIELD_TYPE_CHANGED,
	FIELD_REMOVED,
	FIELD_LESS_ACCESSIBLE,
	FIELD_GENERICS_CHANGED,


	CONSTRUCTOR_REMOVED,
	CONSTRUCTOR_LESS_ACCESSIBLE
}
