package com.github.maracas.roseau.changes;

public enum BreakingChangeKind {
	ANNOTATION_DEPRECATED_ADDED,
	CLASS_REMOVED,
	CLASS_NOW_ABSTRACT,
	CLASS_NOW_FINAL,
	CLASS_NO_LONGER_PUBLIC,
	CLASS_TYPE_CHANGED,
	CLASS_NOW_CHECKED_EXCEPTION,
	CLASS_LESS_ACCESSIBLE,
	CLASS_GENERIC_TEMPLATE_CHANGED,
	CLASS_GENERIC_TEMPLATE_GENERICS_CHANGED,
	SUPERCLASS_REMOVED,
	SUPERCLASS_ADDED,
	SUPERCLASS_MODIFIED_INCOMPATIBLE,
	INTERFACE_ADDED,
	INTERFACE_REMOVED,
	METHOD_REMOVED,    //
	METHOD_REMOVED_IN_SUPERCLASS,
	METHOD_LESS_ACCESSIBLE,  //
	METHOD_LESS_ACCESSIBLE_THAN_IN_SUPERCLASS,
	METHOD_IS_STATIC_AND_OVERRIDES_NOT_STATIC,
	METHOD_RETURN_TYPE_CHANGED,  //
	METHOD_RETURN_TYPE_GENERICS_CHANGED,
	METHOD_PARAMETER_GENERICS_CHANGED,
	METHOD_NOW_ABSTRACT,    //
	METHOD_NOW_FINAL,     //
	METHOD_NOW_STATIC,    //
	METHOD_NO_LONGER_STATIC,    //
	METHOD_NOW_VARARGS,
	METHOD_NO_LONGER_VARARGS,
	METHOD_ADDED_TO_INTERFACE,
	METHOD_ADDED_TO_PUBLIC_CLASS,
	METHOD_NOW_THROWS_CHECKED_EXCEPTION,
	METHOD_NO_LONGER_THROWS_CHECKED_EXCEPTION,
	METHOD_ABSTRACT_ADDED_TO_CLASS,
	METHOD_ABSTRACT_ADDED_IN_SUPERCLASS,
	METHOD_ABSTRACT_ADDED_IN_IMPLEMENTED_INTERFACE,
	METHOD_DEFAULT_ADDED_IN_IMPLEMENTED_INTERFACE,
	METHOD_NEW_DEFAULT,
	METHOD_MOVED_TO_SUPERCLASS,
	METHOD_ABSTRACT_NOW_DEFAULT,  //
	FIELD_STATIC_AND_OVERRIDES_STATIC,
	FIELD_LESS_ACCESSIBLE_THAN_IN_SUPERCLASS,
	FIELD_NOW_FINAL,
	FIELD_NOW_STATIC,
	FIELD_NO_LONGER_STATIC,
	FIELD_TYPE_CHANGED,
	FIELD_REMOVED,
	FIELD_REMOVED_IN_SUPERCLASS,
	FIELD_LESS_ACCESSIBLE,
	FIELD_GENERICS_CHANGED,
	CONSTRUCTOR_REMOVED,
	CONSTRUCTOR_LESS_ACCESSIBLE
}
